name: flutter_bloc_page
description: "Helper package for creating Bloc for controlling one UI Page."
version: 1.1.0
repository: https://github.com/chalermpong/flutter_bloc_page

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  nullable_absent: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.9
  bloc_test: ^9.1.5



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
